name: r2llm
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiohttp-cors==0.8.1
      - aiolimiter==1.2.1
      - aiosignal==1.4.0
      - airportsdata==20250909
      - annotated-types==0.7.0
      - anthropic==0.51.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - apscheduler==3.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - astor==0.8.1
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - autograd==1.8.0
      - azure-core==1.36.0
      - azure-identity==1.22.0
      - babel==2.17.0
      - backrefs==5.9
      - bashlex==0.18
      - beartype==0.12.0
      - beautifulsoup4==4.14.2
      - blake3==1.0.7
      - bleach==6.2.0
      - blessed==1.22.0
      - blinker==1.9.0
      - boto==2.49.0
      - browsergym==0.14.2
      - browsergym-assistantbench==0.14.2
      - browsergym-core==0.14.2
      - browsergym-experiments==0.14.2
      - browsergym-miniwob==0.14.2
      - browsergym-visualwebarena==0.14.2
      - browsergym-webarena==0.14.2
      - browsergym-workarena==0.4.4
      - cachetools==6.2.0
      - cbor2==5.7.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.4.3
      - choreographer==1.2.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - codetiming==1.4.0
      - colorama==0.4.6
      - colorful==0.5.7
      - comm==0.2.3
      - compressed-tensors==0.9.3
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==2.19.0
      - debug-gym==1.2.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - deepspeed==0.18.0
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - depyf==0.18.0
      - diff-parser==1.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - dm-tree==0.1.9
      - dnspython==2.8.0
      - docker==7.1.0
      - dockerfile-parse==2.0.1
      - docstring-parser==0.17.0
      - durationpy==0.10
      - e2b==2.2.5
      - e2b-code-interpreter==2.1.1
      - einops==0.8.1
      - email-validator==2.3.0
      - english-words==2.0.2
      - eval-type-backport==0.2.2
      - evaluate==0.4.6
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - faker==37.11.0
      - farama-notifications==0.0.4
      - fastapi==0.118.2
      - fastapi-cli==0.0.13
      - fastapi-cloud-cli==0.3.1
      - fastcore==1.8.12
      - fastjsonschema==2.21.2
      - fastrlock==0.8.3
      - fastuuid==0.13.5
      - ffmpy==0.6.2
      - filelock==3.20.0
      - fire==0.7.1
      - firecrawl==4.3.6
      - flash-attn==2.7.4.post1
      - flask==3.1.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozendict==2.4.6
      - frozenlist==1.8.0
      - fsspec==2024.3.1
      - gdown==5.2.0
      - gguf==0.17.1
      - ghapi==1.0.8
      - ghp-import==2.1.0
      - gitdb==4.0.12
      - gitignore-parser==0.1.12
      - gitpython==3.1.45
      - google-api-core==2.26.0
      - google-auth==2.41.1
      - google-cloud-aiplatform==1.120.0
      - google-cloud-bigquery==3.38.0
      - google-cloud-core==2.4.3
      - google-cloud-resource-manager==1.14.2
      - google-cloud-storage==2.19.0
      - google-crc32c==1.7.1
      - google-genai==1.42.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - gpustat==1.1.1
      - gradio==5.23.1
      - gradio-client==1.8.0
      - greenlet==3.0.3
      - griffe==1.14.0
      - groovy==0.1.2
      - grpcio==1.51.3
      - grpclib==0.4.8
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==1.2.1
      - h11==0.16.0
      - h2==4.3.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.10
      - hjson==3.1.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.2
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - hyperframe==6.1.0
      - identify==2.6.15
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.0.0
      - iniconfig==2.1.0
      - interegular==0.3.3
      - ipykernel==6.30.1
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.11.0
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kaleido==1.2.0
      - kiwisolver==1.4.9
      - kubernetes==33.1.0
      - lark==1.2.2
      - latex2sympy2==1.9.1
      - lazy-loader==0.4
      - libcst==1.8.5
      - libtmux==0.46.2
      - libvisualwebarena==0.0.15
      - libwebarena==0.0.4
      - liger-kernel==0.6.4
      - lightning-utilities==0.15.2
      - linkify-it-py==2.0.3
      - litellm==1.77.7
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.12
      - logistro==2.0.1
      - lxml==5.4.0
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - matplotlib-venn==1.1.2
      - mcp==1.16.0
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - mistral-common==1.8.5
      - mistune==3.1.4
      - mkdocs==1.6.1
      - mkdocs-autorefs==1.4.3
      - mkdocs-get-deps==0.2.0
      - mkdocs-material==9.6.21
      - mkdocs-material-extensions==1.3.1
      - mkdocstrings==0.30.1
      - mkdocstrings-python==1.18.2
      - modal==1.2.0
      - mpmath==1.3.0
      - msal==1.34.0
      - msal-extensions==1.3.1
      - msgpack==1.1.2
      - msgspec==0.19.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy==1.18.2
      - mypy-extensions==1.1.0
      - narwhals==2.15.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - nltk==3.9.2
      - nodeenv==1.9.1
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - openai==1.99.9
      - openai-harmony==0.0.4
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-exporter-prometheus==0.58b0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.13
      - orjson==3.11.3
      - outcome==1.3.0.post0
      - outlines==0.1.11
      - outlines-core==0.1.26
      - overrides==7.7.0
      - packaging==25.0
      - paginate==0.5.7
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - partial-json-parser==0.2.1.1.post6
      - pathspec==0.12.1
      - peft==0.17.1
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - playwright==1.44.0
      - plotly==6.5.1
      - pluggy==1.6.0
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - portalocker==3.2.0
      - pre-commit==4.3.0
      - prettytable==3.17.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.51
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==4.25.8
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py-spy==0.4.1
      - py4j==0.10.9.7
      - pyarrow==21.0.0
      - pyarrow-hotfix==0.7
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pybind11==3.0.1
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pydantic-extra-types==2.10.6
      - pydantic-settings==2.11.0
      - pydub==0.25.1
      - pyee==11.1.0
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pylatexenc==2.10
      - pymdown-extensions==10.16.1
      - pymupdf==1.26.4
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - pyspark==3.5.0
      - pytest==8.3.5
      - pytest-timeout==2.4.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyvers==0.1.0
      - pyyaml==6.0.2
      - pyyaml-env-tag==1.1
      - pyzmq==27.1.0
      - r2e-gym==0.1.0
      - ray==2.49.2
      - referencing==0.36.2
      - regex==2025.9.18
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.0.0
      - rich-toolkit==0.15.1
      - rignore==0.7.0
      - rllm==0.1.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - ruff==0.14.0
      - sacrebleu==2.5.1
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - sb-cli==0.1.5
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - selenium==4.32.0
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==5.1.1
      - sentencepiece==0.2.1
      - sentry-sdk==2.41.0
      - setproctitle==1.3.7
      - sgl-kernel==0.3.15
      - sglang==0.5.2
      - sglang-router==0.1.9
      - shapely==2.1.2
      - shellingham==1.5.4
      - sigtools==4.0.1
      - simple-parsing==0.1.7
      - simplejson==3.20.2
      - six==1.17.0
      - smart-open==7.3.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - socksio==1.0.0
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - sparklines==0.7.0
      - sse-starlette==3.0.2
      - sseclient-py==1.7.2
      - stack-data==0.6.3
      - starlette==0.48.0
      - swebench==4.0.3
      - swesmith==0.0.4
      - sympy==1.13.1
      - synchronicity==0.10.2
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensordict==0.6.2
      - termcolor==3.1.0
      - terminado==0.18.1
      - text-generation==0.7.0
      - textual==6.2.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.9.0
      - tinycss2==1.4.0
      - together==1.5.26
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.6.0
      - torchao==0.13.0
      - torchaudio==2.6.0
      - torchdata==0.11.0
      - torchmetrics==1.8.2
      - torchvision==0.21.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - tree-sitter==0.25.2
      - tree-sitter-go==0.25.0
      - trio==0.31.0
      - trio-websocket==0.12.2
      - triton==3.2.0
      - typer==0.15.4
      - types-certifi==2021.10.8.3
      - types-python-dateutil==2.9.0.20251008
      - types-requests==2.32.4.20250913
      - types-toml==0.10.8.20240310
      - types-tqdm==4.67.0.20250809
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - tzlocal==5.3.1
      - uc-micro-py==1.0.3
      - unidiff==0.7.5
      - uri-template==1.3.0
      - urllib3==2.3.0
      - uvicorn==0.37.0
      - uvloop==0.21.0
      - verl==0.3.1.dev0
      - vertexai==1.43.0
      - virtualenv==20.35.1
      - vllm==0.8.4
      - wandb==0.22.2
      - watchdog==6.0.0
      - watchfiles==1.1.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - weblinx==0.3.2
      - weblinx-browsergym==0.0.3
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.3
      - wsproto==1.2.0
      - xformers==0.0.29.post2
      - xgrammar==0.1.18
      - xxhash==3.6.0
      - yarl==1.22.0
      - z3-solver==4.15.4.0
      - zipp==3.23.0
