base:
    # Environment configs
    output_path: "exps/swebench-verified"
    benchmark: "swebench-debug"
    problems: "all"  # list of problems, e.g., ["astropy__astropy-12907"], or "all"
    # problems: ["astropy__astropy-7606"]  # list of problems, e.g., ["astropy__astropy-12907"], or "all"
    # problems: ["scikit-learn__scikit-learn-14710"]  # list of problems, e.g., ["astropy__astropy-12907"], or "all"
    # problems: ["sphinx-doc__sphinx-9281"]  # list of problems, e.g., ["astropy__astropy-12907"], or "all"
    # problems: ["django__django-11276"]  # list of problems, e.g., ["astropy__astropy-12907"], or "all"
    # problems: ["astropy__astropy-7336"]  # list of problems, e.g., ["astropy__astropy-12907"], or "all"
    # 排除的问题列表，这些问题将在 run.py 中被统一标记为 error 并跳过运行
    env_kwargs: {
        "dir_tree_depth": 1,
        "run_timeout": 300,
        "dataset_id": "SWE-bench/SWE-bench_Verified",
        "dataset_revision": "99450355ca8c611021187a57ffac304b66666738",
        # shortcut features
        "auto_eval_on_rewrite": False,  # If True, the environment will automatically call the Eval tool after a successful rewrite. If this is set to True, the agent does not need to call the Eval tool itself.
        "show_current_breakpoints": False,  # If True, the environment will automatically show the current breakpoints at every step in the system prompt.
        "show_directory_tree": True,  # If set to True, the environment will show the directory tree in the system prompt.
        "persistent_breakpoints": True,  # If True, the environment will keep a set of breakpoint states across PDB sessions. When a new PDB session is started, the environment will automatically load the breakpoints from the previous session.
        "auto_list": False,  # If True, the environment will automatically call `list .` via the PDB tool after every pdb tool call, which will show the code around the current frame.
    }
    terminal: {
        type: "kubernetes",  # "docker", "kubernetes"
    }

    # LLM configs
    # llm_name: "qwen3-14b-local"
    # llm_name: "qwen3-14b-sft-1121-582step"
    # llm_name: "qwen3-14b-sft-rewrite-1129-590"
    # llm_name: "qwen3-14b-sft-1213-1050step"
    llm_name: "human"
    # llm_name: "qwen3-14b-sft-rewrite-1129-590"
    # llm_name: "qwen2.5-coder-14b-sft-1121-582step"
    # llm_name: "qwen3-14b-local"

    # Agent configs
    random_seed: 42
    max_steps: 80
    max_rewrite_steps: 10
    memory_size: 80
    save_patch: True
    reset_prompt_history_after_rewrite: False
    # Optionally loads a custom system prompt template from a file.
    # system_prompt_template_file: "script/templates/system_prompt.jinja"

rewrite_agent:
    tools: ["grep", "view", "rewrite", "eval"]

debug_agent:
    tools: ["grep", "pdb", "view", "rewrite", "eval"]

solution_agent:
    llm_name: null
    tools: ["eval", "pdb", "submit"]

swe_agent:
    benchmark: "swebench"
    max_steps: 100
    max_rewrite_steps: 10
    tools:
        - bash
        - rewrite
        - submit
